<?php
declare(strict_types=1);

/**
 * Beyond wRVUs value platform. Login-gated page that shares the atlas session. The public-data
 * bundle is decrypted server-side with the session key, the same way api.php serves the atlas data.
 * Generated by BData/women opportunity/platform/export_sgo.py. Edit the template there.
 */
require __DIR__ . '/auth.php';
sgo_boot();
sgo_headers();

if (!sgo_logged_in()) {
    header('Location: ./');
    exit;
}

$nonce = base64_encode(random_bytes(16));
header(
    "Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-" . $nonce . "'; "
    . "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; "
    . "img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"
);

$v = static function (string $rel): string {
    $path = __DIR__ . '/' . $rel;
    $t = is_file($path) ? (string) filemtime($path) : '1';
    return htmlspecialchars($rel . '?v=' . $t, ENT_QUOTES, 'UTF-8');
};

$data = sgo_decrypt_file(__DIR__ . '/data/platform_data.json.enc');
$topo = sgo_decrypt_file(__DIR__ . '/data/platform_topo.json.enc');
if ($data === null || $topo === null) {
    http_response_code(503);
    ?><!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow"><title>Beyond wRVUs Platform</title>
<link rel="stylesheet" href="<?php echo $v('css/app.css'); ?>"></head>
<body><div class="login-wrap"><div class="login-card"><h1>Platform data unavailable</h1>
<p>The platform's data files are missing or can't be decrypted with this session. Sign out and sign in again. If this keeps happening, the files need to be re-encrypted with the current password.</p>
<p><a href="./">Back to the SGO atlas</a> · <a href="logout.php">Sign out</a></p></div></div></body></html>
<?php
    exit;
}

// Keep the JSON inert inside <script>: escape "</" and "<!--" (both valid JSON string escapes).
$embed = static fn(string $json): string => str_replace(['</', '<!--'], ['<\/', '<\u0021--'], $json);
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex, nofollow">
  <meta name="color-scheme" content="light dark">
  <meta name="description" content="Gynecologic oncology program value intelligence: access, supply, economic scenarios, provider footprint, and a local MarketView atlas.">
  <title>Beyond wRVUs Platform</title>
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%23008c80'/%3E%3Cpath d='M8 24h16M11 24V15M16 24V9M21 24v-6' stroke='white' stroke-width='2.4' stroke-linecap='round' fill='none'/%3E%3C/svg%3E">
  <script nonce="<?php echo $nonce; ?>">
    (function () {
      try {
        var t = localStorage.getItem('sgo-theme');
        if (t !== 'light' && t !== 'dark') {
          t = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
        }
        document.documentElement.setAttribute('data-theme', t);
      } catch (e) {}
    })();
  </script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@75..100,500..800&family=Public+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&family=IBM+Plex+Mono:wght@400;500&display=swap">
  <link rel="stylesheet" href="<?php echo $v('css/platform.css'); ?>">
</head>
<body>
<div class="app">
  <aside class="rail" aria-label="Platform navigation">
    <div class="brand">
      <div class="mk">
        <div class="logo" aria-hidden="true"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round"><path d="M4 18h16"/><path d="M7 18V9"/><path d="M12 18V5"/><path d="M17 18v-6"/></svg></div>
        <div class="nm">Beyond wRVUs</div>
      </div>
      <div class="sub">Gyn-onc program value platform</div>
    </div>
    <nav class="nav" id="nav"></nav>
    <div class="rail-foot">
      <div style="text-transform:uppercase;letter-spacing:.08em;font-family:var(--font-mono);font-size:.625rem">Data layers</div>
      <div class="layer-row"><i class="dot live"></i><span>Public layer · CMS 2024, NCI, Census</span></div>
      <div class="layer-row"><i class="dot" id="lic-dot"></i><span id="lic-txt">MarketView · not loaded</span></div>
      <div class="layer-row"><i class="dot off"></i><span>PJI claims · pending license</span></div>
      <div style="margin-top:6px">Prototype by Triaggent for the BData SGO value project. Not for clinical or billing use.</div>
    </div>
  </aside>
  <div class="main">
    <header class="topbar">
      <div class="crumb"><div class="k" id="crumb-k"></div><h1 id="crumb-h"></h1></div>
      <div class="controls">
        <div class="ctl"><span>Geography</span>
          <div class="seg" role="group" aria-label="Geography" id="geo-seg">
            <button type="button" data-geo="us" id="geo-us">United States</button>
            <button type="button" data-geo="mn" id="geo-mn">Minnesota</button>
          </div>
        </div>
        <div class="ctl"><label for="site-sel">Cancer site</label>
          <select id="site-sel">
            <option value="all">All gyn (ovary, uterus, cervix)</option>
            <option value="ov">Ovary</option>
            <option value="ut">Uterus (corpus)</option>
            <option value="cx">Cervix</option>
          </select>
        </div>
      </div>
    </header>
    <main class="view" id="view" tabindex="-1"></main>
  </div>
</div>
<div id="tt" hidden></div>
<div id="drawer-root"></div>
<script src="<?php echo $v('js/vendor/d3.min.js'); ?>"></script>
<script src="<?php echo $v('js/vendor/topojson.min.js'); ?>"></script>
<script type="application/json" id="platform-data"><?php echo $embed($data); ?></script>
<script type="application/json" id="topo-data"><?php echo $embed($topo); ?></script>
<script nonce="<?php echo $nonce; ?>">
  window.SGO_LINKS = [
    { href: './', label: 'SGO atlas', icon: '<path d="M5 21V5l7-2 7 2v16"/><path d="M9 9h.01M15 9h.01M9 13h.01M15 13h.01M10 21v-4h4v4"/>' },
    { theme: true },
    { href: 'logout.php', label: 'Sign out', icon: '<path d="M15 4h3a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1h-3"/><path d="M10 8l-4 4 4 4M6 12h9"/>' }
  ];
</script>
<script src="<?php echo $v('js/platform.js'); ?>"></script>
</body>
</html>
